version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
